# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-09 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outstanding_Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
