# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-21 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.CharField(blank=True, max_length=255, null=True)),
                ('discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('modes', models.CharField(blank=True, max_length=255, null=True)),
                ('tc', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_alph', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('straight_time_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('hourly_bill_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('overtime_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('sp_bill', models.CharField(blank=True, max_length=255, null=True)),
                ('total_bill_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.CharField(blank=True, max_length=255, null=True)),
                ('week_ending_date', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('workers_comp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_po', models.CharField(blank=True, max_length=255, null=True)),
                ('b_w_location_code', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
                ('spcl_paybill_de_code', models.CharField(blank=True, max_length=255, null=True)),
                ('special_paybill_qty', models.CharField(blank=True, max_length=255, null=True)),
                ('special_bill_rate', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
