# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0002_outstanding_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_date', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cash_post_id_memo', models.CharField(blank=True, max_length=255, null=True)),
                ('check', models.CharField(blank=True, max_length=255, null=True)),
                ('recon_key', models.CharField(blank=True, max_length=255, null=True)),
                ('check_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.CharField(blank=True, max_length=255, null=True)),
                ('claim_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=255, null=True)),
                ('explanation_code', models.CharField(blank=True, max_length=255, null=True)),
                ('external_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
