# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0003_payment_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_all',
            name='extra',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
