# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0003_auto_20180525_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
