# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0004_account_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, default=b'BH0000', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mydemo.Batch'),
        ),
    ]
