# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0005_auto_20180525_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(blank=True, default=b'', max_length=255, null=True),
        ),
    ]
