# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0007_auto_20180525_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='batch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
