# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0008_auto_20180525_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='batch_id',
            new_name='batch_no',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='batch_id',
            new_name='batch_no',
        ),
        migrations.RenameField(
            model_name='reconkeys',
            old_name='batch_id',
            new_name='batch_no',
        ),
        migrations.RenameField(
            model_name='timecard',
            old_name='batch_id',
            new_name='batch_no',
        ),
        migrations.RemoveField(
            model_name='reconkeys',
            name='payroll_batch_id',
        ),
        migrations.RemoveField(
            model_name='timecard',
            name='payroll_batch_id',
        ),
        migrations.AddField(
            model_name='reconkeys',
            name='payroll_batch_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecard',
            name='payroll_batch_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
