# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0009_auto_20180525_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reconkeys',
            old_name='payroll_batch_no',
            new_name='payroll_batch_id',
        ),
        migrations.RenameField(
            model_name='timecard',
            old_name='payroll_batch_no',
            new_name='payroll_batch_id',
        ),
    ]
