# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0010_auto_20180525_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard_KT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('time_card_id', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('billable', models.CharField(blank=True, max_length=255, null=True)),
                ('case_manager_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('case_manager_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_time', models.CharField(blank=True, max_length=255, null=True)),
                ('checkout_time', models.CharField(blank=True, max_length=255, null=True)),
                ('client_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_dob', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_id', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_payroll_group', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_payroll_id', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_payroll_rule', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('cosign_staff_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cosign_staff_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('edited_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_number', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('episode_end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('has_split_schedules', models.CharField(blank=True, max_length=255, null=True)),
                ('hcpcs_code', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('medicaid', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('payrolled', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule_status', models.CharField(blank=True, max_length=255, null=True)),
                ('units', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.CharField(blank=True, max_length=255, null=True)),
                ('client_lob', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payer', models.CharField(blank=True, max_length=255, null=True)),
                ('clinician_discipline', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=255, null=True)),
                ('miles', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_batch_id', models.CharField(blank=True, max_length=255, null=True)),
                ('authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ReconKeys',
            new_name='ReconKeys_KT',
        ),
        migrations.DeleteModel(
            name='TimeCard',
        ),
    ]
