# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-25 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0011_auto_20180525_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconKeys_HB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, max_length=255, null=True)),
                ('key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('row_id', models.CharField(blank=True, max_length=255, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=255, null=True)),
                ('post_date', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.CharField(blank=True, max_length=255, null=True)),
                ('client_facility_name', models.CharField(blank=True, max_length=255, null=True)),
                ('shift_date', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('rev_code', models.CharField(blank=True, max_length=255, null=True)),
                ('hcpcs_cpt_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_units', models.CharField(blank=True, max_length=255, null=True)),
                ('orig_charge', models.CharField(blank=True, max_length=255, null=True)),
                ('adjustments', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCard_HB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('time_card_id', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('batch', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('worker_name', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('primary_job_desc', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('standard_pay_method', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('payroll_branch', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('client_branch', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('client_name', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('client_state', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('service_date', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('shift', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('drive_start_time', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('in_home_nva_start_time', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('in_home_nva_end_time', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('service_type', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('rate', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('service_code_rate_type', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('total_time', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('qty', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('payroll_transmittal_group', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('prod_points', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('travel_am', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('travel_tf', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('travel_cv', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('mileage_payment_method', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('service_payable', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('service_payment_method', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('worker_id', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('full_time', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('default_milleage_payment_method', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('worker_class', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('worker_category', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('payroll_department', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('payroll_number', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('expected_prod_points', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('team', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('municipality_code', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('date_of_hire', models.CharField(blank=True, default=b'', max_length=255, null=True)),
                ('uid', models.CharField(blank=True, default=b'', max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reconkeys_kt',
            name='key_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
