# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0012_auto_20180525_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard_kt',
            name='authorization_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecard_kt',
            name='bill_mode_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
