# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0013_auto_20180526_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconkeys_kt',
            name='bill_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
