# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0015_auto_20180527_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='uploaded_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
