# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0016_invoice_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
