# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-30 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0017_auto_20180530_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reconkeys_hb',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reconkeys_kt',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecard_hb',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='timecard_kt',
            name='uploaded_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
