# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0018_auto_20180530_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recon_key', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('difference', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
