# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-31 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0019_cash_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_post',
            name='invoice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cash_post',
            name='payment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cash_post',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
