# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0021_auto_20180605_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_post_id_memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
